### Importing the libraries and datasets

In [64]:
import pandas as pd
import numpy as np

In [65]:
files = [
    "CAvideos.csv",
    "DEvideos.csv",
    "FRvideos.csv",
    "GBvideos.csv",
    "INvideos.csv",
    "JPvideos.csv",
    "KRvideos.csv",
    "MXvideos.csv",
    "RUvideos.csv",
    "USvideos.csv"
]

### Questions

**1. Create a single dataframe with the concatenation of all input csv files, adding a column called country**

In [66]:
all = []

In [67]:
for file in files:
    
    df_temp = pd.read_csv("../data/" + file, encoding="utf-8",encoding_errors="replace")
    
    country = file[:2]   #we need the first character of file name 

    df_temp["country"] = country
    
    all.append(df_temp)
    
    
df = pd.concat(all, ignore_index= True)   #as each df start with index 0, we put true to ignore the index and create a new one for the combined df

In [68]:
df.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description', 'country'],
      dtype='str')

In [69]:
df["country"].unique()

<StringArray>
['CA', 'DE', 'FR', 'GB', 'IN', 'JP', 'KR', 'MX', 'RU', 'US']
Length: 10, dtype: str

these are the countries that are unique through the whole dataset

**2. Extract all videos that have no tag.**

In [70]:
df["tags"].isna().sum()

np.int64(0)

In [71]:
without_tag = df[df["tags"]== "[none]"]

In [72]:
without_tag

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
41,JwboxqDylgg,17.14.11,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,17.14.11,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,17.14.11,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,17.14.11,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,17.14.11,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375815,VGykknw9eCM,18.14.06,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...",Beats by Dre,10,2018-06-07T07:01:06.000Z,[none],3577614,12318,1345,1414,https://i.ytimg.com/vi/VGykknw9eCM/default.jpg,False,False,False,"When your time comes, you have two choices. Yo...",US
375819,fAIX12F6958,18.14.06,Bumblebee (2018) - Official Teaser Trailer - P...,Paramount Pictures,1,2018-06-05T07:00:01.000Z,[none],19864779,228670,16420,46318,https://i.ytimg.com/vi/fAIX12F6958/default.jpg,False,False,False,Every adventure has a beginning. Watch the off...,US
375865,gS1DbvHHVH0,18.14.06,Going in to brain surgery,Simone Giertz,28,2018-05-30T14:22:13.000Z,[none],1635301,120791,1098,20711,https://i.ytimg.com/vi/gS1DbvHHVH0/default.jpg,False,False,False,We’ll post an update on Instagram and Twitter ...,US
375873,E4c7EE8_IX0,18.14.06,Weezer - Africa,weezer,10,2018-05-29T12:00:11.000Z,[none],4682557,115240,5069,9170,https://i.ytimg.com/vi/E4c7EE8_IX0/default.jpg,False,False,False,Stream + download the song: http://fanlink.to/...,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US

the outcome are the videos that do not have any tag

**3. For each channel, determine the total number of views**

In [73]:
df.groupby('channel_title')['views'].sum()

channel_title
! 세상에 무슨일이                3942977
!!8時だよ面白ネタ大集合               50207
!BTS・TWICE まとめ               7310
!Los amorosos Virales¡       6069
!t Live                    240038
                           ...
５分でできる DIY                 272607
ＢＡＳＨｔｖ                     116292
Ｋのフィッシングちゃんねる               37165
ＷＡＪＯＩＫＡ                    424129
💜Sandrea                   347155
Name: views, Length: 37824, dtype: int64

**4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.**

In [74]:
exclud = df[((df['comments_disabled'] == True) & (df['ratings_disabled'] == True)) | (df['video_error_or_removed'] == True)]

In [75]:
exclud.count()

video_id                  2620
trending_date             2620
title                     2620
channel_title             2620
category_id               2620
publish_time              2620
tags                      2620
views                     2620
likes                     2620
dislikes                  2620
comment_count             2620
thumbnail_link            2620
comments_disabled         2620
ratings_disabled          2620
video_error_or_removed    2620
description               2307
country                   2620
dtype: int64

In [76]:
df = df.drop(exclud.index)

In [77]:
df[((df['comments_disabled'] == True) & (df['ratings_disabled'] == True)) | (df['video_error_or_removed'] == True)]

Empty DataFrame
Columns: [video_id, trending_date, title, channel_title, category_id, publish_time, tags, views, likes, dislikes, comment_count, thumbnail_link, comments_disabled, ratings_disabled, video_error_or_removed, description, country]
Index: []

**5. Add a like_ratio column storing the ratio between the number of likes and of dislikes**

We created a new column called like_ratio by dividing the number of likes by the number of dislikes for each video.

Since division by zero is mathematically undefined, we replaced all 0 values in the dislikes column with NaN before calculating the ratio to avoid bias

In [78]:
df["like_ratio"] = df["likes"] / df["dislikes"].replace(0, np.nan)

In [79]:
df['like_ratio']

0          18.135076
1          75.707346
2          27.352500
3          66.485168
4          77.513044
             ...
375937     27.552347
375938    157.089005
375939     46.577519
375940     67.799368
375941      1.676616
Name: like_ratio, Length: 373322, dtype: float64

**6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)**

To group videos published within the same 10-minute interval, we converted each publish time into the total number of minutes.
First, the hour value was converted into minutes and then the minute value was added. After obtaining the total minutes, floor division was used to divide the times into 10-minute intervals to reemove decimal values and ensures that all publish times within the same 10 minute range receive the same cluster label.
This allows us to analyze publishing activity based on grouped time intervals rather than exact timestamps.

In [80]:
df["publish_time"].dtype

In [81]:
df["publish_time"] = pd.to_datetime(df["publish_time"])  #convert them into proper data farame format

In [82]:
df["publish_time"].dt.minute

0          0
1          0
2          5
3          1
4          4
          ..
375937     0
375938     0
375939    34
375940     0
375941     9
Name: publish_time, Length: 373322, dtype: int32

In [83]:
df["cluster"] = (df["publish_time"].dt.minute + df["publish_time"].dt.hour * 60) // 10  #for removing decimals

In [84]:
df.head(15)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,cluster
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,102
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346,102
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500,114
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168,108
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044,66
5,0yIWz1XEeyc,17.14.11,Jake Paul Says Alissa Violet CHEATED with LOGA...,DramaAlert,25,2017-11-13 07:37:51+00:00,"#DramaAlert|""Drama""|""Alert""|""DramaAlert""|""keem...",1309699,103755,4613,12143,https://i.ytimg.com/vi/0yIWz1XEeyc/default.jpg,False,False,False,► Follow for News! - https://twitter.com/KEEMS...,CA,22.491871,45
6,_uM5kFfkhB8,17.14.11,Vanoss Superhero School - New Students,VanossGaming,23,2017-11-12 23:52:13+00:00,"Funny Moments|""Montage video games""|""gaming""|""...",2987945,187464,9850,26629,https://i.ytimg.com/vi/_uM5kFfkhB8/default.jpg,False,False,False,Vanoss Merch Shop: https://vanoss.3blackdot.co...,CA,19.031878,143
7,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57534,2967,15959,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,CA,19.391304,103
8,JzCsM1vtn78,17.14.11,THE LOGANG MADE HISTORY. LOL. AGAIN.,Logan Paul Vlogs,24,2017-11-12 20:19:24+00:00,"logan paul vlog|""logan paul""|""logan""|""paul""|""o...",4477587,292837,4123,36391,https://i.ytimg.com/vi/JzCsM1vtn78/default.jpg,False,False,False,Join the movement. Be a Maverick ► https://Sho...,CA,71.025224,121
9,43sm-QwLcx4,17.14.11,Finally Sheldon is winning an argument about t...,Sheikh Musa,22,2017-11-10 14:10:46+00:00,"God|""Sheldon Cooper""|""Young Sheldon""",505161,4135,976,1484,https://i.ytimg.com/vi/43sm-QwLcx4/default.jpg,False,False,False,Sheldon is roasting pastor of the church\nyoun...,CA,4.236680,85
10,H1KBHFXm2Bg,17.14.11,21 Savage - Bank Account (Official Music Video),21 Savage,10,2017-11-10 19:00:02+00:00,"21 savage|""bank account""|""21 savage bank accou...",5068229,263596,8585,28976,https://i.ytimg.com/vi/H1KBHFXm2Bg/default.jpg,False,False,False,Watch the official music video of Bank Account...,CA,30.704252,114
11,U3xLOo-CNwo,17.14.11,12 Weird Ways To Sneak Food Into Class / Back ...,Troom Troom,26,2017-11-12 15:00:05+00:00,"sneak food|""how to sneak food into class""|""cla...",3153224,28451,2285,3312,https://i.ytimg.com/vi/U3xLOo-CNwo/default.jpg,False,False,False,Subscribe Here: http://bit.ly/2uaz0on\n12 Hot ...,CA,12.451204,90
12,FyZMnhUtLfE,17.14.11,猎场 | Game Of Hunting 12【TV版】（胡歌、張嘉譯、祖峰等主演）,大劇獨播,1,2017-11-12 16:00:01+00:00,"電視劇|""大陸電視劇""|""猎场""|""职场""|""商战""|""爱情""|""都市""|""胡歌""|""陈龙""...",158815,218,30,186,https://i.ytimg.com/vi/FyZMnhUtLfE/default.jpg,False,False,False,Thanks for watching the drama! Help more peopl...,CA,7.266667,96
13,7MxiQ4v0EnE,17.14.11,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,2017-11-11 16:41:15+00:00,"punjabi songs|""punjabi bhangra""|""punjabi music...",5718766,127477,7134,8063,https://i.ytimg.com/vi/7MxiQ4v0EnE/default.jpg,False,False,False,Song - Daang\nSinger - Mankirt Aulakh\nFaceboo...,CA,17.868937,100
14,LUzsOyWp9lw,17.14.11,YOUTUBERS REACT TO TOP 10 TWITTER ACCOUNTS OF ...,FBE,24,2017-11-12 22:00:01+00:00,"twitter|""top 10""|""Taylor Swift""|""YOUTUBERS REA...",960747,31810,668,5335,https://i.ytimg.com/vi/LUzsOyWp9lw/default.jpg,False,False,False,CLICK TO SUBSCRIBE TO THE YOUTUBERS IN THIS EP...,CA,47.619760,132

**7. For each interval, determine the number of videos, average number of likes and of dislikes.**

In [85]:
df.groupby("cluster").size()

cluster
0      2897
1      1509
2      1241
3      1614
4      1269
       ...
139    1554
140    1438
141    1666
142    1466
143    1269
Length: 144, dtype: int64

In [86]:
df.groupby("cluster").agg(
    count_videos = ("video_id", "count"),
    average_likes = ("likes", "mean"),
    average_dislikes = ("dislikes", "mean")
)

         count_videos  average_likes  average_dislikes
cluster
0                2897   61288.115637       3808.149465
1                1509   22748.138502       1449.836315
2                1241   21378.280419       1072.344883
3                1614   36853.560719        955.890954
4                1269   42198.623325       1909.301812
...               ...            ...               ...
139              1554   22783.840412       1110.168597
140              1438   30696.510431       1177.020862
141              1666   18159.173469        874.184874
142              1466   45736.581855       9341.549795
143              1269   10853.743893        505.701340

[144 rows x 3 columns]

**8. For each tag, determine the number of videos**

We consider "none" as a valid tag and therefore do not exclude it from the dataset.

In [87]:
df["tags"].head(20)

0     Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...
1     plush|"bad unboxing"|"unboxing"|"fan mail"|"id...
2     racist superman|"rudy"|"mancuso"|"king"|"bach"...
3     ryan|"higa"|"higatv"|"nigahiga"|"i dare you"|"...
4     edsheeran|"ed sheeran"|"acoustic"|"live"|"cove...
5     #DramaAlert|"Drama"|"Alert"|"DramaAlert"|"keem...
6     Funny Moments|"Montage video games"|"gaming"|"...
7                                       SHANtell martin
8     logan paul vlog|"logan paul"|"logan"|"paul"|"o...
9                  God|"Sheldon Cooper"|"Young Sheldon"
10    21 savage|"bank account"|"21 savage bank accou...
11    sneak food|"how to sneak food into class"|"cla...
12    電視劇|"大陸電視劇"|"猎场"|"职场"|"商战"|"爱情"|"都市"|"胡歌"|"陈龙"...
13    punjabi songs|"punjabi bhangra"|"punjabi music...
14    twitter|"top 10"|"Taylor Swift"|"YOUTUBERS REA...
15    buzzfeed|"buzzfeedblue"|"outsmarted"|"outsmart...
16        prank|"pranks"|"nelk"|"nelkfilmz"|"nelkfilms"
17    Graham Norton|"Graham Norton Show Official"|"E...
18    Rooster Teeth|"RT"|"animation"|"television"|"f...
19    sharry mann|"sharry mann new song"|"sharry man...
Name: tags, dtype: str

In [88]:
df["tag_list"] = df["tags"].str.split("|")

In [89]:
df_exploded = df.explode("tag_list")  #converts each tag from the list into a separate row

In [90]:
df_exploded["tag_list"].value_counts()

tag_list
[none]                             37209
"funny"                            14933
"comedy"                           11962
"2018"                             11029
"news"                              5955
                                   ...
"makeup releases 2018"                 1
"new makeup releases 2018"             1
"new makeup releases"                  1
"trying crayola crayons makeup"        1
"langford"                             1
Name: count, Length: 886936, dtype: int64

**9. Find the tags with the largest number of videos**

In [91]:
tags_count = df_exploded["tag_list"].value_counts()

In [92]:
tags_count.idxmax()

'[none]'

Since "[none]" was previously treated as a valid tag, it appears among the tags with the highest number of videos. However, because it represents videos without tags rather than an actual tag, we exclude it to identify the most frequently used real tag.

In [93]:
tag_count_real = tags_count.drop("[none]")

In [94]:
tag_count_real.idxmax()

'"funny"'

**10. For each (tag, country) pair, compute average ratio likes/dislikes**

In [95]:
df_exploded["average_ratio"] = (
    df_exploded["likes"] / df_exploded["dislikes"].replace(0, np.nan)
)

In [96]:
df_exploded.groupby(["tag_list", "country"])["average_ratio"].mean().reset_index()

,tag_list,country,average_ratio
0,,CA,8.618739
1,,DE,24.344225
2,,FR,16.424636
3,,IN,7.659699
4,,JP,9.894877
...,...,...,...
1136793,ＴＨＥカラオケ★バトル,JP,7.450000
1136794,ｓ１３,JP,15.335714
1136795,🍊 Exatlón México 🍉 programa 🍒 88 EP4-👢 14/02/2...,MX,5.750000
1136796,🔥BROMA A FALCONY EL SUSTO DE SU VIDA🔥,MX,128.516035
1136797,🚀 smartpixel.com.ua,RU,0.714286

**11. For each (trending_date, country) pair, the video with the largest number of views**

In [97]:
index = df.groupby(['trending_date', 'country'])['views'].idxmax()

In [98]:
df.loc[index, ['trending_date', 'country', 'video_id', 'title', 'channel_title', 'views']].reset_index()

,index,trending_date,country,video_id,title,channel_title,views
0,3398,17.01.12,CA,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,56367282
1,44280,17.01.12,DE,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,56367282
2,85252,17.01.12,FR,3VbHg5fqBYw,Avengers: Infinity War Trailer Tease,Marvel Entertainment,7281189
3,126032,17.01.12,GB,TyHvyGVs42U,"Luis Fonsi, Demi Lovato - Échame La Culpa",LuisFonsiVEVO,143408235
4,164617,17.01.12,IN,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,56367282
...,...,...,...,...,...,...,...
1962,216792,18.31.05,JP,aJOTlE1K90k,Maroon 5 - Girls Like You ft. Cardi B,Maroon5VEVO,3057987
1963,251198,18.31.05,KR,ntWSnDV0MYs,[MV] AOA _ Bingle Bangle(빙글뱅글),1theK (원더케이),4150448
1964,291483,18.31.05,MX,xTlNMmZKwpA,"Cardi B, Bad Bunny & J Balvin - I Like It [Off...",Cardi B,20723565
1965,332058,18.31.05,RU,1nX0kF2UwDc,[BadComedian] - Движение Вверх (Плагиат или ве...,BadComedian,3125598
1966,373139,18.31.05,US,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,217750076

The outcome is the most popular content in that countr.

**12. Divide trending_date into three columns: year, month, day**

We first check the data type of trending_date to ensure it is in datetime format before extracting year, month, and day.

In [99]:
df["trending_date"].dtype

In [100]:
df["trending_date"]

0         17.14.11
1         17.14.11
2         17.14.11
3         17.14.11
4         17.14.11
            ...
375937    18.14.06
375938    18.14.06
375939    18.14.06
375940    18.14.06
375941    18.14.06
Name: trending_date, Length: 373322, dtype: str

In [101]:
df[['year', 'day', 'month']] = df['trending_date'].str.split('.', expand = True)

Instead of splitting the date as a string, we can convert trending_date into a proper datetime format.

In [102]:
df["trending_date"] = pd.to_datetime(df["trending_date"], format="%y.%d.%m")

In [103]:
df["year"] = df["trending_date"].dt.year
df["month"] = df["trending_date"].dt.month
df["day"] = df["trending_date"].dt.day

In [104]:
df[["trending_date", "year", "month", "day"]].head()

  trending_date  year  month  day
0    2017-11-14  2017     11   14
1    2017-11-14  2017     11   14
2    2017-11-14  2017     11   14
3    2017-11-14  2017     11   14
4    2017-11-14  2017     11   14

**13. For each (month, country) pair, the video with the largest number of views**

In [105]:
index2 = df.groupby(['month', 'country'])['views'].idxmax()

In [106]:
df.loc[index2, ['month', 'country', 'video_id', 'title', 'channel_title', 'views']].reset_index()

,index,month,country,video_id,title,channel_title,views
0,11214,1,CA,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,43067983
1,51930,1,DE,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,37728802
2,92853,1,FR,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,37728802
3,135208,1,GB,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,90598955
4,173405,1,IN,dfnCAmr569k,"Taylor Swift - End Game ft. Ed Sheeran, Future",TaylorSwiftVEVO,42019590
...,...,...,...,...,...,...,...
72,166769,12,IN,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,125432237
73,224092,12,KR,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,113876217
74,259064,12,MX,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,100912384
75,299087,12,RU,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,52611730
76,341174,12,US,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,149376127

**14. Read all json files with the video categories**

In [107]:
import json
from pathlib import Path
import pandas as pd

In [108]:
categories = Path("../catagories")

In [109]:
json_files = sorted(categories.glob("*_category_id.json"))
print("Founded files:", [p.name for p in json_files])

Founded files: ['CA_category_id.json', 'DE_category_id.json', 'FR_category_id.json', 'GB_category_id.json', 'IN_category_id.json', 'JP_category_id.json', 'KR_category_id.json', 'MX_category_id.json', 'RU_category_id.json', 'US_category_id.json']

In [110]:
json_files

[PosixPath('../catagories/CA_category_id.json'),
 PosixPath('../catagories/DE_category_id.json'),
 PosixPath('../catagories/FR_category_id.json'),
 PosixPath('../catagories/GB_category_id.json'),
 PosixPath('../catagories/IN_category_id.json'),
 PosixPath('../catagories/JP_category_id.json'),
 PosixPath('../catagories/KR_category_id.json'),
 PosixPath('../catagories/MX_category_id.json'),
 PosixPath('../catagories/RU_category_id.json'),
 PosixPath('../catagories/US_category_id.json')]

In [111]:
df2 = []

In [112]:
for jf in json_files:
    country = jf.stem.split("_")[0].upper()  # CA_category_id -> CA

    with open(jf, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    items = data.get("items", [])
    
    cat_df = pd.json_normalize(items)

    cat_df = cat_df[["id", "snippet.title", "snippet.assignable"]].rename(columns={
        "id": "category_id",
        "snippet.title": "category_name",
        "snippet.assignable": "assignable"
    })

    cat_df["category_id"] = cat_df["category_id"].astype(str)
    cat_df["country"] = country

    df2.append(cat_df)

In [113]:
categories_df = pd.concat(df2, ignore_index=True)
categories_df.head()

  category_id     category_name  assignable country
0           1  Film & Animation        True      CA
1           2  Autos & Vehicles        True      CA
2          10             Music        True      CA
3          15    Pets & Animals        True      CA
4          17            Sports        True      CA

In [114]:
categories_df['country'].unique()

<StringArray>
['CA', 'DE', 'FR', 'GB', 'IN', 'JP', 'KR', 'MX', 'RU', 'US']
Length: 10, dtype: str

We load multiple JSON files containing YouTube video category information, extract the relevant fields from the items section, and normalize them into a tabular format. 
For each file, we have the country code from the filename, keep only the category ID, category name, and assignable flag, and add the corresponding country as a new column. 
Finally, all country-specific datasets are combined into a single DataFrame, which provides a unified view of video categories across all regions.

**15. For each country, determine how many videos have a category that is not assignable.**

In [115]:
df["category_id"] = df["category_id"].astype(str)
categories_df["category_id"] = categories_df["category_id"].astype(str)

In [116]:
df_merged = df.merge(
    categories_df[["country", "category_id", "assignable"]],
    on=["country", "category_id"],
    how="left"
)

In [117]:
df_merged

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,video_error_or_removed,description,country,like_ratio,cluster,tag_list,year,day,month,assignable
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,102,"[Eminem, ""Walk"", ""On"", ""Water"", ""Aftermath/Sha...",2017,14,11,True
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,...,False,STill got a lot of packages. Probably will las...,CA,75.707346,102,"[plush, ""bad unboxing"", ""unboxing"", ""fan mail""...",2017,14,11,True
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,...,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500,114,"[racist superman, ""rudy"", ""mancuso"", ""king"", ""...",2017,14,11,True
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,...,False,I know it's been a while since we did this sho...,CA,66.485168,108,"[ryan, ""higa"", ""higatv"", ""nigahiga"", ""i dare y...",2017,14,11,True
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044,66,"[edsheeran, ""ed sheeran"", ""acoustic"", ""live"", ...",2017,14,11,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373317,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,...,False,The Cat Who Caught the Laser - Aaron's Animals,US,27.552347,78,"[aarons animals, ""aarons"", ""animals"", ""cat"", ""...",2018,14,6,True
373318,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[none],1064798,60008,382,...,False,NaN,US,157.089005,6,[[none]],2018,14,6,True
373319,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,...,False,I had so much fun transforming Safiyas hair in...,US,46.577519,105,[I gave safiya nygaard a perfect hair makeover...,2018,14,6,True
373320,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,...,False,How Black Panther Should Have EndedWatch More ...,US,67.799368,102,"[Black Panther, ""HISHE"", ""Marvel"", ""Infinity W...",2018,14,6,True
373321,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,102,"[call of duty, ""cod"", ""activision"", ""Black Ops...",2018,14,6,True

In [63]:
#Check country alignment
print("df countries:", sorted(df["country"].unique()))
print("cat countries:", sorted(categories_df["country"].unique()))

#Check for duplicates in categories_df
print(categories_df.duplicated(subset=["country", "category_id"]).sum())

#Check merge result size vs original
print("Original df:", df.shape[0])
print("Merged df:", df_merged.shape[0])  # should equal df.shape[0] for a clean left join

df countries: ['CA', 'DE', 'FR', 'GB', 'IN', 'JP', 'KR', 'MX', 'RU', 'US']
cat countries: ['CA', 'DE', 'FR', 'GB', 'IN', 'JP', 'KR', 'MX', 'RU', 'US']
0
Original df: 373322
Merged df: 373322

In [118]:
not_assignable_df = df_merged[df_merged["assignable"] == False]
not_assignable_df.shape

(1015, 24)

In [119]:
videos_not_assigned = (
    not_assignable_df
    .groupby("country")
    .size()
    .reset_index(name="videos_not_assigned")
    .sort_values("videos_not_assigned", ascending=False)
)

videos_not_assigned

  country  videos_not_assigned
4      IN                  221
7      RU                  195
5      KR                  167
0      CA                  130
2      FR                  112
1      DE                  110
8      US                   57
3      GB                   20
6      MX                    3

In [120]:
result = (
    df_merged.assign(not_assignable = df_merged["assignable"] == False)
    .groupby("country")["not_assignable"]
    .sum()
    .reset_index(name="videos_not_assigned")
    .sort_values("videos_not_assigned", ascending=False)
)

result

  country  videos_not_assigned
4      IN                  221
8      RU                  195
6      KR                  167
0      CA                  130
2      FR                  112
1      DE                  110
9      US                   57
3      GB                   20
7      MX                    3
5      JP                    0

To determine how many videos belong to non-assignable categories per country, we first ensured that the category_id column in both datasets (df and categories_df) had the same data type (string). This was necessary for a correct merge.

Next, we merged the video dataset with the category dataset using country and category_id as keys, adding the assignable information to each video.

After the merge, we filtered the dataset to keep only videos where the category is not assignable (assignable == False), which allowed us to isolate the relevant records.

We then computed the number of such videos per country using two approaches: first by grouping the filtered dataset and counting rows, and second by creating a boolean indicator for non-assignable videos and summing it per country.

Both methods produced the same result, showing the number of videos in non-assignable categories for each country.